version: '3.7'

services:

  web:
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    image: alerta/alerta-web
    ports:
      - "443:8443"
    volumes:
      - ./config/nginx.conf:/app/nginx.conf
      - ./config/config.json:/web/config.json
      - ./config/alertad.conf:/app/alertad.conf
      - ./config/alerta.conf:/app/alerta.conf
      - ./certs:/app/certs
      - ./audio/alert-disturbing.ogg:/web/audio/alert-disturbing.ogg
    depends_on:
      - db
    environment:
            #- DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://alerta:alerta@db:5432/monitoring
      - AUTH_REQUIRED=True
      - AUTH_PROVIDER=github
      - OAUTH2_CLIENT_ID=9e93e59406f94a62ff9c
      - OAUTH2_CLIENT_SECRET=dc2a9f2b1329bd646a66d748635265039cc9e272
        #- ALLOWED_GITHUB_ORGS=Kpler
      - ADMIN_USERS=@pdelormekpler #default password: alerta
      - ADMIN_KEY=admin-@pdelormekpler-key
      #- ADMIN_USERS=admin@alerta.io #default password: alerta
      #- ADMIN_KEY=admin-key
    restart: always

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: alerta
      POSTGRES_PASSWORD: alerta
    restart: always

